Repository jenkinsci/folder-properties-plugin, pull requests merged in 2025-02, with the labels that each got.

#11 Move documentation to GitHub
  README.md
  docs/images/folder-properties-config.png
  docs/images/folder-properties-freestyle-config.png
  docs/images/freestyle-example-1.png
  docs/images/freestyle-example-scm-1.png
  docs/images/freestyle-example-scm-2.png
  docs/images/freestyle-example-scm-3.png
Labels: documentation

#13 Use correct documentation URL in pom file
  pom.xml
Labels: documentation

#16 Add CODEOWNERS for better review integration
  .github/CODEOWNERS
Labels: chore

#17 Format with spotless
  .gitattributes
  CONTRIBUTING.md
  pom.xml
  src/main/java/com/mig82/folders/properties/FolderProperties.java
  src/main/java/com/mig82/folders/properties/PropertiesLoader.java
  src/main/java/com/mig82/folders/properties/StringProperty.java
  src/main/java/com/mig82/folders/step/FolderPropertiesStep.java
  src/main/java/com/mig82/folders/wrappers/ParentFolderBuildWrapper.java
  src/test/java/com/mig82/folders/FolderPropertiesTest.java
  src/test/java/com/mig82/folders/FreestyleTestHelper.java
  src/test/java/com/mig82/folders/PipelineTestHelper.java
Labels: chore

#19 Enable incrementals for easier development and testing
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#20 Enable continuous delivery on significant merges to master branch
  .github/dependabot.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: enhancement

#24 Restore the options documentation
  README.md
Labels: documentation

#25 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: skip-changelog

#26 Migrate tests to JUnit5
  src/test/java/com/mig82/folders/FolderPropertiesTest.java
  src/test/java/com/mig82/folders/FreestyleTestHelper.java
Labels: test
